name: '[Manual] Release'
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug'
        type: boolean
        default: true
      dry-run:
        description: 'Dry run'
        type: boolean
        default: true

jobs:
  release:
    name: Release
    uses: ./.github/workflows/_release.yml
    with:
      debug: ${{ inputs.debug }}
      dry-run: ${{ inputs.dry-run }}
    secrets: inherit
